### ISSUE TITLE
examples don't track implemented code

### ISSUE THREAD

**Issue by ijsnow** [tauri-apps/tauri-bindgen#100]
The WIP disclaimer at the top of the REAMDE says to feel free to try out the repository but when I copy/paste the examples into my code they don't work. 

It says the host macro should generate a function called `invoke_handler` to pass to `plugin::Builder::invoke_handler` but it doesn't exist.

Could you update the basic example to match the code?

**Comment by JonasKruckenberg** [comment]
Hey, so yeah the examples were outdated because for the longest time this crate broken while I was doing major refactors. 
But, as of yesterday things should work again (and I'm now gearing up for another release)
so I updated the example to reflect the current state. 

Also check out the examples in the examples directory for a full setup
