### ISSUE TITLE
can i share buff by tauri-bindgen?

### ISSUE THREAD

**Issue by yollpoll** [tauri-apps/tauri-bindgen#174]
Currently I need seeding data from rust core to front (vue) by using commands,the problem is that it uses to mach time to trans data (my data is audio's sample data , 20000 data need 40ms),So, I want  to trans data like sharing buffer or other way faster then commands, Can tauri-bindgen helping me?

**Comment by JonasKruckenberg** [comment]
I assume what you want is essentially a shared buffer between Rust and the webview, for zero-copy data sharing. 
This is generally not possible (there are ways for WebView2 on windows now though) because the webviews implementations used don't expose the low-level control necessary. 
Namely we can't access the JS runtime of the webview. If we could the world would look like that utopia meme template.

Something `tauri-bindgen`(and now tauri v2 in a similar manner) does do is replace the much slower JSON encoding for a way more optimized binary encoding and switching out the way messages are sent between the two processes. It still involves copying, but give it a try and see if it's fast enough maybe
